services:

  mir100:
    image: butler/mir100
    build:
      context: ./MiR100/
      dockerfile: Dockerfile-noetic
    privileged: true
    command: >
      sh -c "export ROS_MASTER_URI=http://localhost:11311 &&
            roslaunch mir_driver mir.launch"
    network_mode: "host"

  ur5:
    image: butler/ur5
    build:
      context: ./UR5 Docker/
      dockerfile: Dockerfile
    privileged: true
    tty: true
    stdin_open: true
    command: sh
    network_mode: "host"

  realsense:
    image: butler/realsense
    build:
      context: ./realsense
      dockerfile: Dockerfile.realsense
    privileged: true     # würde container alles geben (nicht optimal)
#    devices:       
#      - "/dev/bus:/dev/bus"   # gibt ordner mit usb geräten an containern weiter
    command: roslaunch realsense2_camera rs_camera.launch --wait
    network_mode: host
